# MODE:
#     test_list:
#         - test_News_Base
#         - test_News_Auto  


DATASET:
    data_path: /workspace/code/bait_news_gen/data # all data folder
    max_word_len: 512
    fake_path: None # which Auto
    fake_name: fake_top1_90_99.csv # 생성된 파일이름


TRAIN:
    batch_size: 4
    num_training_steps: 5000
    accumulation_steps: 1
    use_wandb: True

    log_interval: 50
    eval_interval: 1000

    OPTIMIZER:
        lr: 0.00001
        weight_decay: 0.0005

    SCHEDULER:
        warmup_ratio: 0.1
        use_scheduler: True

TEST:
    batch_size: 64
    log_interval: 10
    saved_model_path : None

RESULT:
    savedir: ../results