MODE:
    test_list:
        - test_News_Base
        - test_News_Auto  


DATASET:
    data_path: /root/code/bait_news_gen/data # all data folder
    #bait_path: None
    max_word_len: 512
    model_sort: None # News_Base or News_Auto
    bait_sort: None # which Auto


TRAIN:
    batch_size: 8
    num_training_steps: 10000
    accumulation_steps: 1
    use_wandb: True

    log_interval: 50
    eval_interval: 1000

    OPTIMIZER:
        lr: 0.00001
        weight_decay: 0.0005

    SCHEDULER:
        warmup_ratio: 0.1
        use_scheduler: True

TEST:
    batch_size: 64
    log_interval: 10
    saved_model_path : None

RESULT:
    savedir: ../saved_model