datadir: '/workspace/code/bait_news_gen/data'
savedir: '/workspace/code/bait_news_gen/data/Fake'
METHOD:
  name: 'tfidf'
  target: 'title-content'
  source : 'title-content'
  select_name: 'tfidf_full_full_all'
  extract : 'all'
  topk : 3
SEED: 42