datadir: '../data/Part1'
savedir: '../data-direct'
METHOD:
  name: 'tfidf'
  target: 'title-content'
  source : 'title-content'
  select_name: 'tfidf_full_full_all'
  extract : 'all'
  topk : 5
SEED: 42