datadir: '../data/Part1' 
savedir: '../data-direct'
METHOD:
  name: 'bm25'
  target: 'title-content'
  source : 'title-content'
  select_name : 'bm25_title_content_category_select'
  extract : 'all'
SEED: 42